import { type WordCard } from './types';

export const words: WordCard[] = [
  { id: 1, english: 'apple', russian: 'яблоко' },
  { id: 2, english: 'book', russian: 'книга' },
  { id: 3, english: 'cat', russian: 'кот' },
  { id: 4, english: 'dog', russian: 'собака' },
  { id: 5, english: 'house', russian: 'дом' },
  { id: 6, english: 'car', russian: 'машина' },
  { id: 7, english: 'tree', russian: 'дерево' },
  { id: 8, english: 'flower', russian: 'цветок' },
  { id: 9, english: 'water', russian: 'вода' },
  { id: 10, english: 'sun', russian: 'солнце' },
  { id: 11, english: 'moon', russian: 'луна' },
  { id: 12, english: 'star', russian: 'звезда' },
  { id: 13, english: 'friend', russian: 'друг' },
  { id: 14, english: 'family', russian: 'семья' },
  { id: 15, english: 'school', russian: 'школа' },
  { id: 16, english: 'teacher', russian: 'учитель' },
  { id: 17, english: 'student', russian: 'ученик' },
  { id: 18, english: 'computer', russian: 'компьютер' },
  { id: 19, english: 'phone', russian: 'телефон' },
  { id: 20, english: 'table', russian: 'стол' },
  { id: 21, english: 'chair', russian: 'стул' },
  { id: 22, english: 'window', russian: 'окно' },
  { id: 23, english: 'door', russian: 'дверь' },
  { id: 24, english: 'food', russian: 'еда' },
  { id: 25, english: 'bread', russian: 'хлеб' },
  { id: 26, english: 'milk', russian: 'молоко' },
  { id: 27, english: 'coffee', russian: 'кофе' },
  { id: 28, english: 'happy', russian: 'счастливый' },
  { id: 29, english: 'beautiful', russian: 'красивый' },
  { id: 30, english: 'love', russian: 'любовь' },
];